name: CI/CD for Compose Multiplatform App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build Android APK
        run: ./gradlew :androidApp:assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Android APK
          path: androidApp/build/outputs/apk/debug/*.apk

  ios-build:
    name: Build iOS
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app

      - name: Install CocoaPods
        run: pod install --project-directory=iosApp

      - name: Build iOS Framework
        run: ./gradlew :iosApp:build

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: iOS Build
          path: iosApp/build/*

  desktop-build:
    name: Build Desktop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build Desktop Executable
        run: ./gradlew :desktopApp:package

      - name: Upload Desktop Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Desktop Executable
          path: desktopApp/build/distributions/*
